# Generated by Django 4.2.7 on 2023-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='Catagory',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(max_length=200, upload_to='product_image/'),
        ),
    ]
